### ISSUE TITLE
OIDC Auth Fails: Incorrect query parameter scopes generated instead of scope

### ISSUE THREAD

**Issue by rajin4463** [statping-ng/statping-ng#353]
StatPing version: v0.93.0
PocketID version: 1.16.0

Hi Team,

I am trying to configure OIDC authentication (using Pocket ID as the provider). The authentication flow initiates, but the provider immediately rejects the request with a "Scope is required" error.

Looking at the generated authorisation URL, I noticed that Statping is appending the scopes using the query parameter scopes (plural). The OAuth 2.0 and OpenID Connect require this parameter to be named scope (singular). Upon changing the url parameter to scope instead of scopes manually I was able to authenticate correctly.

**Steps to Reproduce:**

```
1. Configure a Custom OIDC/OAuth provider in Settings.
2. Set the Scopes field to email,profile.
3. Save and attempt to authenticate via the new provider.
4. Observe the URL generated in the browser address bar.
```

**Expected Behaviour:** 

```
The user should be authenticated and redirected towards the StatPing instance
```

**Comment by jemand771** [comment]
should have been fixed by https://github.com/statping-ng/statping-ng/pull/322 but apparently wasn't :(

**Comment by rajin4463** [comment]
@jemand771 Hi,

Small update: I have not touched the configuration on Statping, but authentication has started working randomly. The Statping version is still `Statping-ng 0.93.0`.

The only recent change was integrating my LLDAP into Pocket ID, though I don't see how that would trigger Statping to "magically" start working. For context, I am hosting all of my services on Docker through DokPloy.

If you would like any logs, please let me know and I'll be happy to post them. If needed, I can also provide access to my instance since it is just a fresh test/lab environment with no sensitive data.

Thank you for your help and to the team for creating and maintaining this tool.

**Comment by kerniger** [comment]
unfortunately i have the same problem, also with pocketid. Problem is still, that the url-parameter is "scopes" instead of "scope"
